######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 26 21:43:36 2007
######################################################################

TEMPLATE = app
TARGET = deskitem
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += deskitem.h
FORMS += deskitem.ui
SOURCES += deskitem.cpp main.cpp

TRANSLATIONS    = ../../files/lng/deskitem_ar.ts \
                  ../../files/lng/deskitem_nl.ts \
                  ../../files/lng/deskitem_es.ts \
                  ../../files/lng/deskitem_fr.ts \
                  ../../files/lng/deskitem_tr.ts

INCLUDEPATH += ../../include
LIBS		+= -L../../lib -lhde2
