######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 27 22:35:17 2007
######################################################################

TEMPLATE = app
TARGET = hxkb
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += hxkbwidget.h
SOURCES += hxkbwidget.cpp main.cpp

INCLUDEPATH	+= ../../include /usr/X11R6/include
LIBS	+= -L../../lib -lhde2


TRANSLATIONS    = ../../files/lng/hxkb_ar.ts \
                  ../../files/lng/hxkb_nl.ts \
                  ../../files/lng/hxkb_es.ts \
                  ../../files/lng/hxkb_fr.ts \
                  ../../files/lng/hxkb_tr.ts

